### ISSUE TITLE
私聊中戳一戳时，会调用PlatformAdapterQQOneBot.GetGroupMemberInfo()导致nil报错程序退出

### ISSUE THREAD

**Issue by Szzrain** [sealdice/sealdice#52]
该问题引起的报错不会留下crashlog，且在新版本中出现，需要加急修复。
目前暂行的解决方式：关闭qq戳一戳功能或者使用手表协议

**Comment by Szzrain** [comment]
报错信息如下：

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x109e582]

goroutine 873 [running]:
sealdice-core/dice.(*PlatformAdapterQQOnebot).GetGroupMemberInfo(0xc0002e61c0, 0xc0002b2870?, 0xc0009dbe80?)
        C:/Users/MSI-NB/GolandProjects/sealdice-core/dice/platform_adapter_qq_actions.go:273 +0x162
sealdice-core/dice.(*PlatformAdapterQQOnebot).packTempCtx(0xc0002e61c0, 0xc00098a7e0, 0xc003553c20)
        C:/Users/MSI-NB/GolandProjects/sealdice-core/dice/platform_adapter_qq.go:853 +0xd7
sealdice-core/dice.(*PlatformAdapterQQOnebot).Serve.func3.4()
        C:/Users/MSI-NB/GolandProjects/sealdice-core/dice/platform_adapter_qq.go:686 +0x46
created by sealdice-core/dice.(*PlatformAdapterQQOnebot).Serve.func3
        C:/Users/MSI-NB/GolandProjects/sealdice-core/dice/platform_adapter_qq.go:685 +0x17bc

**Comment by Szzrain** [comment]
fixed
